version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    container_name: swagger_ui
    ports:
      - "8080:8080"
    volumes:
      - ./doc/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: